### ISSUE TITLE
Mọi người kiếm xong tục ngữ chưa z... 

### ISSUE THREAD

**Issue by Hung7Luu** [Hung7Luu/Lop-10A12-Nhom-8#9]

**Comment by HuyenVoPN** [comment]
alo mọi người

**Comment by HuyenVoPN** [comment]
giờ tìm câu tục ngữ, lấy câu này được không: "Có mới nới cũ, mới để trong nhà, cũ để ngoài sân"

**Comment by nhuhuynh10a12** [comment]
mà tụi bây định làm chủ đề gì

**Comment by HuyenVoPN** [comment]
:)))) hong biết nữa

**Comment by nhuhuynh10a12** [comment]
> giờ tìm câu tục ngữ, lấy câu này được không: "Có mới nới cũ, mới để trong nhà, cũ để ngoài sân"

kím cái nào dễ dễ xíu đi bà

**Comment by HuyenVoPN** [comment]
:)))))))))) để tìm cái nào zui zui xem

**Comment by HuyenVoPN** [comment]
eei không thấy

**Comment by ChiThien10c12** [comment]
học sinh mà, lấy mấy câu ca dao tục ngữ về chủ đề học tập đi

**Comment by HuyenVoPN** [comment]
Gần mực thì đen, gần đèn thì sáng ?????????

**Comment by nhuhuynh10a12** [comment]
ăn quả nhớ kẻ trồng cây đc khum :))
biết ơn các thứ đồ lun

**Comment by ChiThien10c12** [comment]
ừ lấy mấy câu về lòng biết ơn các kiểu cũng ok đấy

**Comment by HuyenVoPN** [comment]
ê thế t thích uống nước dừa

**Comment by HuyenVoPN** [comment]
lấy uống nước nhớ nguồn đc  ko :))))

**Comment by ChiThien10c12** [comment]
m điên hả thiện, lòng biết ơn chắc nhiều nhóm lấy rồi
giờ m lấy lại chi nữa

**Comment by ChiThien10c12** [comment]
m mới điên ấy, chốt câu "Uống nước nhớ nguồn" đi

**Comment by HuyenVoPN** [comment]
Thiện bị hack hả Thiện

**Comment by nhuhuynh10a12** [comment]
> ê thế t thích uống nước dừa

liên quan ghê chưa

**Comment by HuyenVoPN** [comment]
gì đa nhân cách zậy

**Comment by Hung7Luu** [comment]
Rồi chốt đi

**Comment by Hung7Luu** [comment]
Lấy cái nào nè mng..

**Comment by HuyenVoPN** [comment]
UỐNG NƯỚC NHỚ NGUỒNNN

**Comment by nhuhuynh10a12** [comment]
> UỐNG NƯỚC NHỚ NGUỒNNN

cái này cx đc nè

**Comment by Hung7Luu** [comment]
Rồi ok nha chốt Ăn quả nhớ kẻ trồng cây :))

**Comment by ChiThien10c12** [comment]
chốt uống nước nhớ nguồn đi

**Comment by ChiThien10c12** [comment]
không chừng tí thằng thiện nó đòi câu khác nữa mệt lắm í

**Comment by nhuhuynh10a12** [comment]
> Rồi ok nha chốt Ăn quả nhớ kẻ trồng cây :))
ủa mắc cừi z thằng này

**Comment by Hung7Luu** [comment]
Nhà m nuôi hai Thiện hả

**Comment by HuyenVoPN** [comment]
ủa khoan

**Comment by nhuhuynh10a12** [comment]
> không chừng tí thằng thiện nó đòi câu khác nữa mệt lắm í
khùng hả m

**Comment by HuyenVoPN** [comment]
Thiện bị trầm cảm hay đa nhân cách hả

**Comment by Hung7Luu** [comment]
Bị mắc covid xong biến chứng sang chuyện tâm lí hả :)?

**Comment by HuyenVoPN** [comment]
Hay là bài tập deadline nhìu quá rồi úng não

**Comment by ChiThien10c12** [comment]
đừng có nói z thiện nó buồn nó cọc lên bây giờ á

**Comment by ChiThien10c12** [comment]
chốt lẹ đi nào

**Comment by Hung7Luu** [comment]
Kh có gì mặc cảm kả, xung quanh t toàn f0 t vẫn lạc quan lắm -_-

**Comment by nhuhuynh10a12** [comment]
> Bị mắc covid xong biến chứng sang chuyện tâm lí hả :)?

ũa r m test chưa Hưng

**Comment by HuyenVoPN** [comment]
UỐNG NƯỚC NHỚ NGUỒN ĐÊ!!!!!!!!!!!!!!!!!!!

**Comment by HuyenVoPN** [comment]
> Kh có gì mặc cảm kả, xung quanh t toàn f0 t vẫn lạc quan lắm -_-

:)))) j z máa

**Comment by Hung7Luu** [comment]
> 

Mai tính :)))

**Comment by Hung7Luu** [comment]
Ủa

**Comment by Hung7Luu** [comment]
Reply tin nhắn sao z

**Comment by HuyenVoPN** [comment]
nhấn 3 chấm -> quote reply 

> Reply tin nhắn sao z

**Comment by nhuhuynh10a12** [comment]
> Reply tin nhắn sao z

kaka khum bít rep tn :))

**Comment by Hung7Luu** [comment]
> > Reply tin nhắn sao z
> 
> kaka khum bít rep tn :))

Yo im pro now

**Comment by ChiThien10c12** [comment]
gà quá Hưng ơi 🐔

> Reply tin nhắn sao z

**Comment by Baogiang24** [comment]
Ủa vậy chốt ăn quả nhớ kẻ trồng cây hả mn?

**Comment by Hung7Luu** [comment]
> Ủa vậy chốt ăn quả nhớ kẻ trồng cây hả mn?
Ừ ÷)

**Comment by HuyenVoPN** [comment]
nố nồ nô
UỐNG NƯỚC NHỚ NGUỒN cơ !!!!!!!!!!!!!!!!!1111

**Comment by nhuhuynh10a12** [comment]
thoi uống nước đi mọi người

**Comment by HuyenVoPN** [comment]
dịch dã covid, uoongs nước dừa đi mọi ngườiiiiiii

**Comment by nhuhuynh10a12** [comment]
tự nhiên quay xe thấy uống nước dễ viết hơn

**Comment by Hung7Luu** [comment]
> nố nồ nô UỐNG NƯỚC NHỚ NGUỒN cơ !!!!!!!!!!!!!!!!!1111

Nhóm trưởng quyết, miễn cự cãi..!

**Comment by Hung7Luu** [comment]
Ăn khoai đi

**Comment by HuyenVoPN** [comment]
cho trưởng làm cảm nhận

**Comment by nhuhuynh10a12** [comment]
> > nố nồ nô UỐNG NƯỚC NHỚ NGUỒN cơ !!!!!!!!!!!!!!!!!1111
> 
> Nhóm trưởng quyết, miễn cự cãi..!
chúng toi đòi quyền dân chủ @HuyenVoPN

**Comment by Hung7Luu** [comment]
Khoai có rấc nhìu ví ta mìn

**Comment by HuyenVoPN** [comment]
> > > nố nồ nô UỐNG NƯỚC NHỚ NGUỒN cơ !!!!!!!!!!!!!!!!!1111
> > 
> > 
> > Nhóm trưởng quyết, miễn cự cãi..!
> > chúng toi đòi quyền dân chủ @HuyenVoPN

:))))))))))))))))) có cuộc khởi nghĩa đứng lên giành quyền bây h

**Comment by Baogiang24** [comment]
Sao nãy ai đòi tục ngữ liên quan tới học tập?
Học thầy không tày học bạn thì seo

**Comment by Hung7Luu** [comment]
> cho trưởng làm cảm nhận

Putin mới nhắn bảo t là ổng thích câu uống nước nhớ nguồn hơn =))

**Comment by Hung7Luu** [comment]
Quyết Uống nước nhớ nguồn nha

**Comment by HuyenVoPN** [comment]
:)))))))))) con Hưng này

**Comment by nhuhuynh10a12** [comment]
> Sao nãy ai đòi tục ngữ liên quan tới học tập? Học thầy không tày học bạn thì seo

nó quay xe lẹ r m

**Comment by HuyenVoPN** [comment]
cho hỏi vụ U cà sao rồi

**Comment by HuyenVoPN** [comment]
> Sao nãy ai đòi tục ngữ liên quan tới học tập? Học thầy không tày học bạn thì seo

hoyyy, học bạn gì mà ngồi cười khằng khặc

**Comment by Baogiang24** [comment]
Vậy thôi, nhớ nguồn thì nhớ nguồn
M mà có chép mạng thì NHỚ ghi NGUỒN nha @Hung7Luu

**Comment by ChiThien10c12** [comment]
ủa vậy là chốt xong chưa, t hơi bùồn ngủ rồi

**Comment by ChiThien10c12** [comment]
mới gần 12h ngủ gì m 
mai có học sáng đâu

**Comment by nhuhuynh10a12** [comment]
> mới gần 12h ngủ gì m mai có học sáng đâu

ui cha thằng này khùm thiệc hả tụi bây

**Comment by Baogiang24** [comment]
Ê t bắt đầu sợ r nha Thiện, bị rén á:))))
